import type { Product, Coupon, Order } from "./types";
import chocolateCake from "@/assets/product-chocolate-cake.jpg";
import redVelvet from "@/assets/product-red-velvet.jpg";
import cupcakes from "@/assets/product-cupcakes.jpg";
import croissant from "@/assets/product-croissant.jpg";
import sourdough from "@/assets/product-sourdough.jpg";
import mangoCheesecake from "@/assets/product-mango-cheesecake.jpg";
import strawberryTart from "@/assets/product-strawberry-tart.jpg";
import butterscotch from "@/assets/product-butterscotch.jpg";
import weddingCake from "@/assets/product-wedding-cake.jpg";
import danish from "@/assets/product-danish.jpg";
import baguette from "@/assets/product-baguette.jpg";

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Belgian Chocolate Truffle",
    description: "Rich dark chocolate ganache layered cake with truffle shavings.",
    price: 899,
    image: chocolateCake,
    category: "cakes",
    occasions: ["birthday", "anniversary", "casual"],
    flavour: "chocolate",
    rating: 4.9,
    isVeg: true,
    isAvailable: true,
    bestSeller: true,
    stock: 12,
  },
  {
    id: "p2",
    name: "Classic Red Velvet",
    description: "Velvety red sponge with smooth cream cheese frosting.",
    price: 749,
    image: redVelvet,
    category: "cakes",
    occasions: ["birthday", "anniversary"],
    flavour: "redVelvet",
    rating: 4.8,
    isVeg: true,
    isAvailable: true,
    bestSeller: true,
    stock: 8,
  },
  {
    id: "p3",
    name: "Vanilla Sprinkle Cupcakes",
    description: "Pack of 6 fluffy vanilla cupcakes with rainbow sprinkles.",
    price: 360,
    image: cupcakes,
    category: "cupcakes",
    occasions: ["birthday", "babyShower", "casual"],
    flavour: "vanilla",
    rating: 4.7,
    isVeg: true,
    isAvailable: true,
    stock: 24,
  },
  {
    id: "p4",
    name: "Butter Croissant",
    description: "Flaky French butter croissant baked fresh every morning.",
    price: 95,
    image: croissant,
    category: "pastries",
    occasions: ["casual"],
    flavour: "vanilla",
    rating: 4.6,
    isVeg: true,
    isAvailable: true,
    bestSeller: true,
    stock: 40,
  },
  {
    id: "p5",
    name: "Artisan Sourdough",
    description: "Slow-fermented crusty sourdough loaf with open crumb.",
    price: 280,
    image: sourdough,
    category: "bread",
    occasions: ["casual"],
    flavour: "vanilla",
    rating: 4.5,
    isVeg: true,
    isAvailable: true,
    stock: 18,
  },
  {
    id: "p6",
    name: "Alphonso Mango Cheesecake",
    description: "Creamy no-bake cheesecake topped with fresh Alphonso mango.",
    price: 650,
    image: mangoCheesecake,
    category: "cakes",
    occasions: ["birthday", "casual"],
    flavour: "mango",
    rating: 4.9,
    isVeg: true,
    isAvailable: true,
    bestSeller: true,
    stock: 6,
  },
  {
    id: "p7",
    name: "Strawberry Cream Tart",
    description: "Buttery shortcrust tart filled with vanilla cream and berries.",
    price: 320,
    image: strawberryTart,
    category: "pastries",
    occasions: ["casual", "anniversary"],
    flavour: "vanilla",
    rating: 4.7,
    isVeg: true,
    isAvailable: true,
    stock: 15,
  },
  {
    id: "p8",
    name: "Butterscotch Caramel Cake",
    description: "Soft sponge soaked in butterscotch caramel with crunchy bits.",
    price: 720,
    image: butterscotch,
    category: "cakes",
    occasions: ["birthday", "casual"],
    flavour: "butterscotch",
    rating: 4.6,
    isVeg: true,
    isAvailable: true,
    stock: 9,
  },
  {
    id: "p9",
    name: "Two-Tier Wedding Cake",
    description: "Custom two-tier fondant cake with sugar flowers (made to order).",
    price: 4500,
    image: weddingCake,
    category: "custom",
    occasions: ["wedding", "anniversary"],
    flavour: "vanilla",
    rating: 5,
    isVeg: true,
    isAvailable: true,
    stock: 3,
  },
  {
    id: "p10",
    name: "Chocolate Danish",
    description: "Buttery flaky pastry with melted chocolate filling.",
    price: 120,
    image: danish,
    category: "pastries",
    occasions: ["casual"],
    flavour: "chocolate",
    rating: 4.5,
    isVeg: true,
    isAvailable: true,
    stock: 30,
  },
  {
    id: "p11",
    name: "Rustic Baguette",
    description: "Traditional French baguette with golden crust and airy crumb.",
    price: 180,
    image: baguette,
    category: "bread",
    occasions: ["casual"],
    flavour: "vanilla",
    rating: 4.4,
    isVeg: true,
    isAvailable: true,
    stock: 22,
  },
  {
    id: "p12",
    name: "Choco-Chip Cupcakes",
    description: "Pack of 6 chocolate cupcakes loaded with choco chips.",
    price: 420,
    image: cupcakes,
    category: "cupcakes",
    occasions: ["birthday", "casual"],
    flavour: "chocolate",
    rating: 4.7,
    isVeg: true,
    isAvailable: true,
    stock: 18,
  },
];

export const COUPONS: Coupon[] = [
  { code: "BAKE20", discountPct: 20, minOrderValue: 500 },
  { code: "WELCOME10", discountPct: 10, minOrderValue: 200 },
];

export const SAMPLE_ORDERS: Order[] = [
  {
    id: "BE2041",
    date: "2025-04-22",
    items: [
      { name: "Belgian Chocolate Truffle", quantity: 1, price: 899 },
      { name: "Butter Croissant", quantity: 2, price: 95 },
    ],
    total: 1089,
    status: "out_for_delivery",
    paymentMethod: "upi",
    deliveryType: "delivery",
    address: "Bandra West, Mumbai",
  },
  {
    id: "BE2032",
    date: "2025-04-18",
    items: [{ name: "Classic Red Velvet", quantity: 1, price: 749 }],
    total: 749,
    status: "delivered",
    paymentMethod: "cod",
    deliveryType: "delivery",
    address: "Andheri East, Mumbai",
  },
  {
    id: "BE2025",
    date: "2025-04-10",
    items: [{ name: "Vanilla Sprinkle Cupcakes", quantity: 2, price: 360 }],
    total: 720,
    status: "delivered",
    paymentMethod: "upi",
    deliveryType: "pickup",
    address: "Powai Store",
  },
  {
    id: "BE2018",
    date: "2025-04-02",
    items: [{ name: "Two-Tier Wedding Cake", quantity: 1, price: 4500 }],
    total: 4500,
    status: "cancelled",
    paymentMethod: "upi",
    deliveryType: "delivery",
    address: "Juhu, Mumbai",
  },
];

export const REVENUE_LAST_7_DAYS = [
  { day: "Mon", revenue: 12400 },
  { day: "Tue", revenue: 9800 },
  { day: "Wed", revenue: 14600 },
  { day: "Thu", revenue: 11200 },
  { day: "Fri", revenue: 18900 },
  { day: "Sat", revenue: 24500 },
  { day: "Sun", revenue: 21300 },
];

export const INGREDIENTS = [
  { name: "All-purpose Flour", stock: 45, unit: "kg", reorder: 20 },
  { name: "Castor Sugar", stock: 12, unit: "kg", reorder: 15 },
  { name: "Butter (Amul)", stock: 8, unit: "kg", reorder: 10 },
  { name: "Dark Chocolate (55%)", stock: 22, unit: "kg", reorder: 10 },
  { name: "Cream Cheese", stock: 4, unit: "kg", reorder: 6 },
  { name: "Fresh Cream", stock: 18, unit: "L", reorder: 10 },
  { name: "Eggs", stock: 240, unit: "pcs", reorder: 100 },
  { name: "Vanilla Extract", stock: 3, unit: "L", reorder: 2 },
];
